# Generated by Django 3.1.7 on 2021-03-08 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('timestamp', models.IntegerField()),
                ('status', models.CharField(choices=[('o', 'open'), ('c', 'closed'), ('a', 'cancelled'), ('e', 'expired')], max_length=1)),
                ('type', models.CharField(choices=[('m', 'market'), ('l', 'limit')], max_length=1)),
                ('side', models.CharField(choices=[('b', 'buy'), ('s', 'sell')], max_length=1)),
                ('cost', models.DecimalField(decimal_places=10, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=10)),
                ('filled', models.DecimalField(decimal_places=10, max_digits=10)),
                ('remaining', models.DecimalField(decimal_places=10, max_digits=10)),
                ('fee_currency', models.CharField(max_length=4)),
                ('fee', models.DecimalField(decimal_places=10, max_digits=10)),
                ('fee_rate', models.DecimalField(decimal_places=10, max_digits=10)),
            ],
        ),
    ]
